// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtwE9uFUlwbgp53kbBLnaM3nojJApHZgU',
    appId: '1:52012436929:web:06a058f7c619cf5f27f340',
    messagingSenderId: '52012436929',
    projectId: 'music-player-5cdb4',
    authDomain: 'music-player-5cdb4.firebaseapp.com',
    storageBucket: 'music-player-5cdb4.appspot.com',
    measurementId: 'G-CVWDVCW4W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ErkH0usd24z_-t4FpJjqPcNoxg-Acd4',
    appId: '1:52012436929:android:5c5f69c8de0da5ff27f340',
    messagingSenderId: '52012436929',
    projectId: 'music-player-5cdb4',
    storageBucket: 'music-player-5cdb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoF6OrBZ2GXQ0VX2OKY5TDtWvAI5FSeD4',
    appId: '1:52012436929:ios:b8b90d4c9a4aff9c27f340',
    messagingSenderId: '52012436929',
    projectId: 'music-player-5cdb4',
    storageBucket: 'music-player-5cdb4.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoF6OrBZ2GXQ0VX2OKY5TDtWvAI5FSeD4',
    appId: '1:52012436929:ios:7eebd1892aa12ff827f340',
    messagingSenderId: '52012436929',
    projectId: 'music-player-5cdb4',
    storageBucket: 'music-player-5cdb4.appspot.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
